version: '3'

services:
  flask_wrapper:
    container_name: flask_wrapper
    restart: always
    build: ./flask_wrapper
    ports:
      - "8080:8080"
#    command: gunicorn -w 3 -b 0.0.0.0:8080 --timeout 0 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_wrapper
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/ :ro
      - ./certbot/www:/var/www/certbot/ :ro
      - ./certbot/conf:/etc/nginx/ssl/ :ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/ :rw
      - ./certbot/conf:/etc/letsencrypt/ :rw